### ISSUE TITLE
PCB/Panel out of stock

### ISSUE THREAD

**Issue by LeonardEyer** [jakplugg/Orgone-accumulator#2]
Hello! I'd love to build this module of yours. Is it possible to buy a PCB somewhere (EU)?
I could also make them myself if you decide to open source it.

Greetings!

**Comment by jakplugg** [comment]
I think i will release the panel files as open source, and just sell
boards. good idea. I should have them up in the next couple of weeks.

**Comment by LeonardEyer** [comment]
So the PCB will be in stock again soon?

**Comment by jasonnolan** [comment]
Synthcube has them in stock in multiple formats. https://synthcube.com/cart/neutron-sound-orgone-accumulator-euro-format

**Comment by chmanie** [comment]
Is there any shop in Europe that'd sell me the PCB?

**Comment by jakplugg** [comment]
Sorry, I have not heard of any. A synth diy shop can get them from michigan
synth works, but if they order just 1 I expect it will cost more than you
ordering it yourself.
